### ISSUE TITLE
How can I see stock level? 

### ISSUE THREAD

**Issue by dan5082** [ndgigliotti/shopify-spy#8]
Is stock level available for all stores? For the ones I have tried in the result all I see it `'inventory_management': 'shopify'` 

Thanks for the cool library and the help!

**Comment by ndgigliotti** [comment]
Hey, sorry for the late response. No, inventory level may not be available in some stores. I've noticed that the fields can vary. In addition, some stores may just leave certain fields blank.

If inventory level has disappeared from all stores, it's likely due to Shopify making a change on their end. I haven't used this for a while, but I suspect it's just the particular store you're interested in.

**Comment by fabioselau077** [comment]
resolved?
